### ISSUE TITLE
wrong platform

### ISSUE THREAD

**Issue by omarmerheb** [krishealty/venom-instagram-bruteforce#1]
cp: cannot create regular file '/data/data/com.termux/files/usr/etc/tor': No such file or directory

____    ____  _______ .__   __.   ______   .___  ___.
\   \  /   / |   ____||  \ |  |  /  __  \  |   \/   |
 \   \/   /  |  |__   |   \|  | |  |  |  | |  \  /  |
  \      /   |   __|  |  . `  | |  |  |  | |  |\/|  |
   \    /    |  |____ |  |\   | |  `--`  | |  |  |  |
    \__/     |_______||__| \__|  \______/  |__|  |__|

        >>  Script By HACKER X PHANTOM(XPH4N70M) << 

       >>  JOIN US NOW :  https://bit.ly/3PV3S3r  << 

[1] 10M Password Attack
[2] Custom Password Attack
[3] Exit

[*] Choose an option: 2
main.sh: line 49: cd: /data/data/com.termux/files/home/venom-instagram-bruteforce/custom-pass: No such file or directory
bash: custom-pass.sh: No such file or directory
 
it seems to be treating my kali linux machine as if its a termux emulator i was never prompted to specify what my platform is

**Comment by krishealty** [comment]
Hey there, The tool was mainly for Termux users and this error is because of the directory path. To solve the issue please simply:

**change the directory path from the script where your files of this program are saved.**

In my case it worked by simply changing 

`data/com.termux/files/home/venom-instagram-bruteforce/custom-pass`

to

`root/venom-instagram-bruteforce/custom-pass`
